# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: http

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: http
    steps:
    - uses: actions/checkout@v3

    - name: remove_http_docker_container
      run: (sudo docker stop http_container || true) && (sudo docker image rm -f http_server || true) && (sudo docker rm -f http_container || true)
    - name: build_http_container
      working-directory: ./http_server
      run: sudo docker build --platform linux/arm64 ./ -t http_server
    - name: run_http_container
      run: sudo docker run -d --restart unless-stopped -p 80:8080 --name http_container http_server
